force-app/main/default/objects/FO_immediate_attention_delay__mdt/FO_immediate_attention_delay__mdt.object-meta.xml
<CustomObject>
    <label>FO immediate attention delay</label>
    <pluralLabel>FO immediate attention delays</pluralLabel>
</CustomObject>

force-app/main/default/objects/FO_immediate_attention_delay__mdt/fields/Number_Of_Hours__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Hours__c</fullName>
    <label>Number Of Hours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CheckFulfillmentOrders_Batch.cls
public class CheckFulfillmentOrders_Batch Implements Database.Batchable<FulfillmentOrder>, Database.Stateful {

    public Iterable<FulfillmentOrder> start(Database.BatchableContext bc) {
        FO_immediate_attention_delay__mdt fOImmediateAttentionDelayMdt = 
            [SELECT Number_Of_Hours__c FROM FO_immediate_attention_delay__mdt];

        datetime searchDate = datetime.now().addHours(-fOImmediateAttentionDelayMdt.Number_Of_Hours__c.intValue());
    
        return [SELECT Id, Status
                FROM FulfillmentOrder
                WHERE OrderSummary.OrderedDate < =: searchDate 
                AND StatusCategory = 'Fulfilling' AND Status != 'Require Immediate attention' ];        
    }

    public void execute(Database.BatchableContext bc, List<FulfillmentOrder> fulfillmentOrders){
        for (FulfillmentOrder fulfillmentOrder : fulfillmentOrders){
            fulfillmentOrder.Status = 'Require Immediate attention';            
        }
        update fulfillmentOrders;
    }

    public void finish(Database.BatchableContext bc){
        
    }
}